### ISSUE TITLE
Report error in case of module lint fails

### ISSUE THREAD

**Issue by kanthesha** [MetaMask/module-lint#75]
Now, when we run a `yarn run-tool` on a project, even when there're fails or even error, it is been resolved instead of throwing.
Output in console now.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c31c6bfd4f2dd59d782f6b550d54109c5e90eb9/Screenshot%202024-03-27%20at%2014.35.43.png" alt="Screenshot 2024-03-27 at 14.35.43.png" />

We would like to throw an error.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3NWQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--970709cee4aa7760a76147b5106f3f7b6bc0139d/Screenshot%202024-03-27%20at%2014.34.55.png" alt="Screenshot 2024-03-27 at 14.34.55.png" />

**Comment by mcmire** [comment]
For more context here, we need the tool to exit with a non-zero exit code if there are any lint errors or if the tool throws an error for any reason. This way, when running the tool in a GitHub workflow, the job will fail (as right now it would still show as running successfully, since we catch all errors).
